version: '3'
services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/
    env_file:
      - db.env
    ports:
      - 15432:5432
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
  simple-auth-sw:
    image: wst24365888/simple-auth-sw:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - database
    volumes:
      - ./weaver.toml/:/app/weaver.toml
    command: 
      - "weaver"
      - "multi"
      - "deploy"
      - "weaver.toml"
volumes:
  pgdata:
